import { Component ,Input } from '@angular/core';

@Component({
  selector: 'app-text-content',
  templateUrl: './text-content.component.html',
  styleUrls: ['./text-content.component.css']
})
export class TextContentComponent {

  buttons=["AutoComplete","Badge","Bottom Sheet","Button","Button toggle","Card","checkbox","chips","Dialog","divider","core","form field","chips","datepicker","input","menu","list","progress bar"]

public isCollapsed = false;






  content=["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus autem impedit fugit inventore ducimus facere minus est, ad itaque odit sunt obcaecati id earum eius aliquam soluta necessitatibus blanditiis rem eligendi! Atque ullam fuga possimus suscipit assumenda dolores architecto esse commodi quibusdam eum, amet dolor tempore distinctio explicabo nam, veritatis cum eos quas voluptates qui recusandae officiis enim. Alias animi excepturi dolor deserunt autem aperiam vitae error reprehenderit voluptas ab, vero sint aspernatur illum repellendus quisquam, quas quos at facere soluta aut. Quae vel magni, ab voluptas est exercitationem debitis, adipisci, quisquam placeat doloribus aliquam ullam illo nemo molestiae corporis veniam! Asperiores, doloremque suscipit voluptas eum sit debitis! Tempora recusandae, fugit qui sunt voluptate eius impedit id similique ut in molestiae inventore atque repellendus nesciunt dolor quidem expedita? Doloribus consequuntur, minus ipsa enim ullam facilis eos voluptatibus explicabo impedit atque distinctio? Quis nobis sapiente dolores enim laboriosam voluptates animi vitae ducimus molestiae et qui, aliquam eveniet consequatur porro voluptatibus facere sed! Quos, aperiam minima debitis labore eveniet ratione perferendis facere, dolor rerum esse unde quas voluptatem dolorum doloribus temporibus libero voluptatibus recusandae. Odio iusto cum repellat modi soluta nostrum error laborum suscipit esse quod impedit minus culpa eveniet accusamus minima aliquam cupiditate sequi porro optio deserunt eligendi, voluptatibus vel voluptatum? Eligendi eaque, vitae ad adipisci quam, odio voluptatum ex soluta aut aperiam asperiores quas enim? Quaerat ratione sit, vitae assumenda eligendi ipsum repudiandae quam? Quis est, numquam sequi blanditiis voluptate ex totam sed, non laudantium impedit nemo, rerum molestias exercitationem?",
"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus autem impedit fugit inventore ducimus facere minus est, ad itaque odit sunt obcaecati id earum eius aliquam soluta necessitatibus blanditiis rem eligendi! Atque ullam fuga possimus suscipit assumenda dolores architecto esse commodi quibusdam eum, amet dolor tempore distinctio explicabo nam, veritatis cum eos quas voluptates qui recusandae officiis enim. Alias animi excepturi dolor deserunt autem aperiam vitae error reprehenderit voluptas ab, vero sint aspernatur illum repellendus quisquam, quas quos at facere soluta aut. Quae vel magni, ab voluptas est exercitationem debitis, adipisci, quisquam placeat doloribus aliquam ullam illo nemo molestiae corporis veniam! Asperiores, doloremque suscipit voluptas eum sit debitis! Tempora recusandae, fugit qui sunt voluptate eius impedit id similique ut in molestiae inventore atque repellendus nesciunt dolor quidem expedita? Doloribus consequuntur, minus ipsa enim ullam facilis eos voluptatibus explicabo impedit atque distinctio? Quis nobis sapiente dolores enim laboriosam voluptates animi vitae ducimus molestiae et qui, aliquam eveniet consequatur porro voluptatibus facere sed! Quos, aperiam minima debitis labore eveniet ratione perferendis facere, dolor rerum esse unde quas voluptatem dolorum doloribus temporibus libero voluptatibus recusandae. Odio iusto cum repellat modi soluta nostrum error laborum suscipit esse quod impedit minus culpa eveniet accusamus minima aliquam cupiditate sequi porro optio deserunt eligendi, voluptatibus vel voluptatum? Eligendi eaque, vitae ad adipisci quam, odio voluptatum ex soluta aut aperiam asperiores quas enim? Quaerat ratione sit, vitae assumenda eligendi ipsum repudiandae quam? Quis est, numquam sequi blanditiis voluptate ex totam sed, non laudantium impedit nemo, rerum molestias exercitationem?",
"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus autem impedit fugit inventore ducimus facere minus est, ad itaque odit sunt obcaecati id earum eius aliquam soluta necessitatibus blanditiis rem eligendi! Atque ullam fuga possimus suscipit assumenda dolores architecto esse commodi quibusdam eum, amet dolor tempore distinctio explicabo nam, veritatis cum eos quas voluptates qui recusandae officiis enim. Alias animi excepturi dolor deserunt autem aperiam vitae error reprehenderit voluptas ab, vero sint aspernatur illum repellendus quisquam, quas quos at facere soluta aut. Quae vel magni, ab voluptas est exercitationem debitis, adipisci, quisquam placeat doloribus aliquam ullam illo nemo molestiae corporis veniam! Asperiores, doloremque suscipit voluptas eum sit debitis! Tempora recusandae, fugit qui sunt voluptate eius impedit id similique ut in molestiae inventore atque repellendus nesciunt dolor quidem expedita? Doloribus consequuntur, minus ipsa enim ullam facilis eos voluptatibus explicabo impedit atque distinctio? Quis nobis sapiente dolores enim laboriosam voluptates animi vitae ducimus molestiae et qui, aliquam eveniet consequatur porro voluptatibus facere sed! Quos, aperiam minima debitis labore eveniet ratione perferendis facere, dolor rerum esse unde quas voluptatem dolorum doloribus temporibus libero voluptatibus recusandae. Odio iusto cum repellat modi soluta nostrum error laborum suscipit esse quod impedit minus culpa eveniet accusamus minima aliquam cupiditate sequi porro optio deserunt eligendi, voluptatibus vel voluptatum? Eligendi eaque, vitae ad adipisci quam, odio voluptatum ex soluta aut aperiam asperiores quas enim? Quaerat ratione sit, vitae assumenda eligendi ipsum repudiandae quam? Quis est, numquam sequi blanditiis voluptate ex totam sed, non laudantium impedit nemo, rerum molestias exercitationem?",
"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus autem impedit fugit inventore ducimus facere minus est, ad itaque odit sunt obcaecati id earum eius aliquam soluta necessitatibus blanditiis rem eligendi! Atque ullam fuga possimus suscipit assumenda dolores architecto esse commodi quibusdam eum, amet dolor tempore distinctio explicabo nam, veritatis cum eos quas voluptates qui recusandae officiis enim. Alias animi excepturi dolor deserunt autem aperiam vitae error reprehenderit voluptas ab, vero sint aspernatur illum repellendus quisquam, quas quos at facere soluta aut. Quae vel magni, ab voluptas est exercitationem debitis, adipisci, quisquam placeat doloribus aliquam ullam illo nemo molestiae corporis veniam! Asperiores, doloremque suscipit voluptas eum sit debitis! Tempora recusandae, fugit qui sunt voluptate eius impedit id similique ut in molestiae inventore atque repellendus nesciunt dolor quidem expedita? Doloribus consequuntur, minus ipsa enim ullam facilis eos voluptatibus explicabo impedit atque distinctio? Quis nobis sapiente dolores enim laboriosam voluptates animi vitae ducimus molestiae et qui, aliquam eveniet consequatur porro voluptatibus facere sed! Quos, aperiam minima debitis labore eveniet ratione perferendis facere, dolor rerum esse unde quas voluptatem dolorum doloribus temporibus libero voluptatibus recusandae. Odio iusto cum repellat modi soluta nostrum error laborum suscipit esse quod impedit minus culpa eveniet accusamus minima aliquam cupiditate sequi porro optio deserunt eligendi, voluptatibus vel voluptatum? Eligendi eaque, vitae ad adipisci quam, odio voluptatum ex soluta aut aperiam asperiores quas enim? Quaerat ratione sit, vitae assumenda eligendi ipsum repudiandae quam? Quis est, numquam sequi blanditiis voluptate ex totam sed, non laudantium impedit nemo, rerum molestias exercitationem?",
"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus autem impedit fugit inventore ducimus facere minus est, ad itaque odit sunt obcaecati id earum eius aliquam soluta necessitatibus blanditiis rem eligendi! Atque ullam fuga possimus suscipit assumenda dolores architecto esse commodi quibusdam eum, amet dolor tempore distinctio explicabo nam, veritatis cum eos quas voluptates qui recusandae officiis enim. Alias animi excepturi dolor deserunt autem aperiam vitae error reprehenderit voluptas ab, vero sint aspernatur illum repellendus quisquam, quas quos at facere soluta aut. Quae vel magni, ab voluptas est exercitationem debitis, adipisci, quisquam placeat doloribus aliquam ullam illo nemo molestiae corporis veniam! Asperiores, doloremque suscipit voluptas eum sit debitis! Tempora recusandae, fugit qui sunt voluptate eius impedit id similique ut in molestiae inventore atque repellendus nesciunt dolor quidem expedita? Doloribus consequuntur, minus ipsa enim ullam facilis eos voluptatibus explicabo impedit atque distinctio? Quis nobis sapiente dolores enim laboriosam voluptates animi vitae ducimus molestiae et qui, aliquam eveniet consequatur porro voluptatibus facere sed! Quos, aperiam minima debitis labore eveniet ratione perferendis facere, dolor rerum esse unde quas voluptatem dolorum doloribus temporibus libero voluptatibus recusandae. Odio iusto cum repellat modi soluta nostrum error laborum suscipit esse quod impedit minus culpa eveniet accusamus minima aliquam cupiditate sequi porro optio deserunt eligendi, voluptatibus vel voluptatum? Eligendi eaque, vitae ad adipisci quam, odio voluptatum ex soluta aut aperiam asperiores quas enim? Quaerat ratione sit, vitae assumenda eligendi ipsum repudiandae quam? Quis est, numquam sequi blanditiis voluptate ex totam sed, non laudantium impedit nemo, rerum molestias exercitationem?"]

}
